name: dagger

on:
  push:
    branches: [main]

env:
  CI_PROJECT_NAME: ${{ github.repository }}
  CI_PROJECT_URL: ${{ github.repositoryUrl }}
  CI_COMMIT_SHA: ${{ github.sha }}
  CI_COMMIT_BRANCH: ${{ github.ref_name }}
  CI_DEFAULT_BRANCH: main
  CI_REGISTRY: ghcr.io
  CI_REGISTRY_USER: ${{ github.actor }}
  CI_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  CI_REGISTRY_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - run: go run ./ci
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
